### ISSUE TITLE
Wrong detect hour with 60 minutes

### ISSUE THREAD

**Issue by lexin** [ChernyshenkoTaras/TimeIntervalPicker#5]
TimeIntervalPicker.swift
line # 303
let hour = selectedMinute <= 60 ? 0 : selectedMinute / 60
            
Maybe it's better to use   selectedMinute <60 
1 hour it's 60 minutes sharp.

**Comment by ChernyshenkoTaras** [comment]
@lexin I will look on that issue shortly.

**Comment by lexin** [comment]
The problem still exists. 
When select 1 hour, next time open picker - and selected time is 0-0
https://www.dropbox.com/s/081j2x2speau36b/TimeTrackerProblem.mov?dl=0

**Comment by lexin** [comment]
It was Ok to have only minutes, and value equals 60. But the problem with second time open and selected time view

**Comment by ChernyshenkoTaras** [comment]
@lexin it should be fixed now. Please update your pods and let me know if you will have any issues
